version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      # - "443:443" # descomente quando adicionar SSL
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./logs:/var/log/nginx
    networks:
      - lubbic_net
      # - lubpicking_net
      # - mindro_net

networks:
  lubbic_net:
    external: true
  # lubpicking_net:
  #   external: true
  # mindro_net:
  #   external: true
